<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\HospitalProntuario.Domain\HospitalProntuario.Domain.csproj" />
    <ProjectReference Include="..\HospitalProntuario.Infra\HospitalProntuario.Infra.csproj" />
  </ItemGroup>

</Project>
